name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # need tags to generate release notes

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/0.7.9/install.sh | sh

    - name: Run ruff
      run: |
        uv run ruff check radiacode radiacode-examples
        uv run ruff format --check radiacode radiacode-examples

    - name: Build wheel
      id: build
      run: |
        uv build

    - name: Release Notes
      run: |
        echo '## Changes since previous release:' > changelog.md
        git log --oneline $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- [%h](https://github.com/cdump/radiacode/commit/%H) %s" >> changelog.md

    - name: Github Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body_path: changelog.md
        files: |
          dist/*

    - name: Publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv publish
