name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/0.7.9/install.sh | sh

    - name: Ruff
      run: |
        sudo apt-get install -y libglib2.0-dev
        uv run ruff check radiacode radiacode-examples
        uv run ruff format --check radiacode radiacode-examples

    # TODO
    # - name: Run tests
    #   run: |
    #     poetry run pytest -ra -v
